name: smoke
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - jupyterlab
  - polars
  - pip
  - pip:
      - pre-commit
      - flake8
      - mypy
  